apiVersion: batch/v1
kind: CronJob
metadata:
  name: ngrok-sync
  namespace: atlantis
spec:
  # Run every 2 hours.
  schedule: '0 */2 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ngrok
          initContainers:
            # Bump the trigger ConfigMap to cause Atlantis to restart
            - name: ngrok-restart
              image: kubefirst/git-helper
              imagePullPolicy: Always
              args:
                [
                  'sync',
                  'webhook',
                  'ngrok-atlantis',
                  '--provider',
                  '$(GIT_PROVIDER)',
                  '--owner',
                  '$(GIT_OWNER)',
                  '--repository',
                  '$(GIT_REPOSITORY)',
                  '--restart',
                ]
            # Give the tunnel long enough to restart
            - name: wait
              image: busybox
              command: ['/bin/sh', '-c']
              args: ['sleep 10']
            - name: wait-for-atlantis
              image: busybox
              command:
                [
                  'sh',
                  '-c',
                  'until nc -z atlantis.atlantis.svc.cluster.local 80 > /dev/null; do echo Waiting for atlantis to be ready; sleep 2; done;',
                ]
          containers:
            # Update upstream webhook with new ngrok tunnel information
            - name: ngrok-sync
              image: kubefirst/git-helper
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: k3d-ngrok
              args:
                [
                  'sync',
                  'webhook',
                  'ngrok-atlantis',
                  '--provider',
                  '$(GIT_PROVIDER)',
                  '--owner',
                  '$(GIT_OWNER)',
                  '--repository',
                  '$(GIT_REPOSITORY)',
                ]
          restartPolicy: Never
