apiVersion: batch/v1
kind: Job
metadata:
  name: ngrok-startup
  namespace: atlantis
spec:
  template:
    spec:
      serviceAccountName: ngrok
      containers:
        # Update upstream webhook with new ngrok tunnel information
        - name: ngrok-startup
          image: kubefirst/git-helper
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: k3d-ngrok
          args:
            [
              'sync',
              'webhook',
              'ngrok-atlantis',
              '--provider',
              '$(GIT_PROVIDER)',
              '--owner',
              '$(GIT_OWNER)',
              '--repository',
              '$(GIT_REPOSITORY)',
            ]
      restartPolicy: OnFailure
