apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: atlantis

resources:
  - configmap.yaml
  - cronjob.yaml
  - deployment.yaml
  - job.yaml
  - rbac.yaml
  - service.yaml

images:
  - name: ngrok
    newName: ngrok/ngrok
    newTag: '3'
  - name: kubefirst/git-helper
    newName: eb129/git-helper
    newTag: 'v1.0.0'

generatorOptions:
  disableNameSuffixHash: true
