---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ngrok
  namespace: atlantis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ngrok
  namespace: atlantis
rules:
  - apiGroups: ['']
    resources: ['configmaps', 'secrets']
    verbs:
      ['get', 'watch', 'list', 'create', 'apply', 'patch', 'delete', 'update']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ngrok
  namespace: atlantis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ngrok
subjects:
  - kind: ServiceAccount
    name: ngrok
