apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app.kubernetes.io/name: nginx-apex
    app.kubernetes.io/instance: nginx-apex
spec:
  type: NodePort
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: nginx-apex
    app.kubernetes.io/instance: nginx-apex
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30001
