apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - job.yaml
  - rbac.yaml

images:
  - name: kubefirst/vault-handler
    newName: eb129/vault-handler
    newTag: 'v0'

generatorOptions:
  disableNameSuffixHash: true
